src/EasyERP.Web/Models/Payments/PaymentModel.cs
namespace EasyERP.Web.Models.Payments
{
    using System;
    using EasyERP.Web.Framework.Mvc;

    public class PaymentModel : BaseEntityModel
    {
        public double TotalAmount { get; set; }

        public double Paid { get; set; }

        public DateTime DueDateTime { get; set; }
    }

    public class PayItemModel
    {
        public int Id { get; set; }

        //public DateTime PayDate { get; set; }

        public double PayAmount { get; set; }
    }
}

src/EasyERP.Web/Controllers/PaymentController.cs
namespace EasyERP.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Doamin.Service.Payments;
    using Domain.Model.Payments;
    using EasyERP.Web.Models.Payments;

    public class PaymentController : Controller
    {
        private readonly IPaymentService paymentService;

        public PaymentController(IPaymentService paymentService)
        {
            this.paymentService = paymentService;
        }

        public ActionResult PayInfo(int id)
        {
            var payment = paymentService.GetPaymentById(id);
            if (payment == null)
            {
                return new HttpNotFoundResult();
            }

            var paymentModel = new PaymentModel
            {
                Id = payment.Id,
                DueDateTime = payment.DueDateTime,
                TotalAmount = payment.TotalAmount,
                Paid = payment.Items.Sum(i => i.Paid)
            };

            return View(paymentModel);
        }

        [HttpPost]
        public ActionResult PayInfo(PaymentModel model)
        {
            if (ModelState.IsValid)
            {
                var payment = paymentService.GetPaymentById(model.Id);
                if (payment == null)
                {
                    return new HttpNotFoundResult();
                }

                var item = payment.Items.Select(
                    i => new
                    {
                        PayDate = i.PayDataTime,
                        PayAmount = i.Paid
                    });

                return Json(item);
            }

            return RedirectToAction(
                "PayInfo",
                new
                {
                    model.Id
                });
        }

        [HttpPost]
        public ActionResult Pay(PayItemModel model)
        {
            if (ModelState.IsValid)
            {
                var payment = paymentService.GetPaymentById(model.Id);
                if (payment == null)
                {
                    return new HttpNotFoundResult();
                }

                payment.Items.Add(
                    new PayItem
                    {
                        PayDataTime = DateTime.Now,
                        Paid = model.PayAmount
                    });

                paymentService.UpdatePayment(payment);
            }

            return RedirectToAction(
                "PayInfo",
                new
                {
                    model.Id
                });
        }
    }
}

src/EasyERP.Web/Controllers/ProductController.cs
namespace EasyERP.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Doamin.Service.ExportImport;
    using Doamin.Service.Helpers;
    using Doamin.Service.Products;
    using Doamin.Service.Security;
    using Doamin.Service.Stores;
    using Domain.Model.Payments;
    using Domain.Model.Products;
    using EasyERP.Web.Extensions;
    using EasyERP.Web.Framework.Kendoui;
    using EasyERP.Web.Framework.Mvc;
    using System.Runtime.Remoting.Messaging;
    using System.Security.Permissions;
    using WebGrease.Css.Extensions;   
    using EasyERP.Web.Models.Products;
    using Infrastructure;

    public class ProductController : BaseAdminController
    {
        private readonly ICategoryService categoryService;

        private readonly IDateTimeHelper dateTimeHelper;

        private readonly IExportManager exportManager;

        private readonly IInventoryService inventoryService;

        private readonly IPermissionService permissionService;

        private readonly IProductPriceService productPriceService;

        private readonly IProductService productService;

        private readonly IStoreService storeService;

        public ProductController(
            IPermissionService permissionService,
            ICategoryService categoryService,
            IProductService productService,
            IStoreService storeService,
            IProductPriceService productPriceService,
            IInventoryService inventoryService,
            IDateTimeHelper dateTimeHelper,
            IExportManager exportManager)
        {
            this.permissionService = permissionService;
            this.categoryService = categoryService;
            this.productService = productService;
            this.storeService = storeService;
            this.productPriceService = productPriceService;
            this.inventoryService = inventoryService;
            this.dateTimeHelper = dateTimeHelper;
            this.exportManager = exportManager;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult ProductList(DataSourceRequest command, ProductListModel model)
        {
            if (!permissionService.Authorize(StandardPermissionProvider.GetProductList))
            {
                return AccessDeniedView();
            }

            if (ModelState.IsValid)
            {
                var categoryIds = new List<int>
                {
                    model.SearchCategoryId
                };

                var storeIds = new List<int>
                {
                    0
                };

                var products = productService.SearchProducts(
                    categoryIds: categoryIds,
                    storeIds: storeIds,
                    keywords: model.SearchProductName,
                    pageIndex: command.Page - 1,
                    pageSize: command.PageSize
                    );
                var gridModel = new DataSourceResult
                {
                    Data = products.Select(
                        x =>
                        {
                            var productModel = x.ToModel();
                            var price = productPriceService.GetProductPrice(model.SearchStoreId, x.Id);
                            productModel.Price = price.SalePrice;
                            productModel.ProductCost = price.CostPrice;
                            productModel.FullDescription = "";

                            return productModel;
                        }),
                    Total = products.TotalCount
                };

                return Json(gridModel);
            }
            return Json(false);
        }

        public ActionResult List()
        {
            if (!permissionService.Authorize(StandardPermissionProvider.GetProductList))
            {
                return AccessDeniedView();
            }
            var model = new ProductListModel();

            //categories
            model.AvailableCategories.Add(
                new SelectListItem
                {
                    Text = "所有目录",
                    Value = "0"
                });

            var categories = categoryService.GetAllCategories();
            foreach (var c in categories)
            {
                model.AvailableCategories.Add(
                    new SelectListItem
                    {
                        Text = c.Name,
                        Value = c.Id.ToString()
                    });
            }

            //stores
            //model.AvailableStores.Add(
            //    new SelectListItem
            //    {
            //        Text = "所有店面",
            //        Value = "0"
            //    });
            var stores = storeService.GetAllStores();
            foreach (var store in stores)
            {
                model.AvailableStores.Add(
                    new SelectListItem
                    {
                        Text = store.Name,
                        Value = store.Id.ToString()
                    });
            }

            model.AvailablePublishedOptions.Add(
                new SelectListItem
                {
                    Text = "所有",
                    Value = "0"
                });
            model.AvailablePublishedOptions.Add(
                new SelectListItem
                {
                    Text = "已发布",
                    Value = "1"
                });
            model.AvailablePublishedOptions.Add(
                new SelectListItem
                {
                    Text = "未发布",
                    Value = "2"
                });

            return View(model);
        }

        public ActionResult Inventory()
        {
            if (!permissionService.Authorize(StandardPermissionProvider.InventoryProduct))
            {
                return AccessDeniedView();
            }
            var model = new ProductListModel();

            //categories
            model.AvailableCategories.Add(
                new SelectListItem
                {
                    Text = "所有目录",
                    Value = "0"
                });

            var categories = categoryService.GetAllCategories();
            foreach (var c in categories)
            {
                model.AvailableCategories.Add(
                    new SelectListItem
                    {
                        Text = c.Name,
                        Value = c.Id.ToString()
                    });
            }

            //stores
            //model.AvailableStores.Add(
            //    new SelectListItem
            //    {
            //        Text = "所有店面",
            //        Value = "0"
            //    });
            var stores = storeService.GetAllStores();
            foreach (var store in stores)
            {
                model.AvailableStores.Add(
                    new SelectListItem
                    {
                        Text = store.Name,
                        Value = store.Id.ToString()
                    });
            }

            model.AvailablePublishedOptions.Add(
                new SelectListItem
                {
                    Text = "所有",
                    Value = "0"
                });
            model.AvailablePublishedOptions.Add(
                new SelectListItem
                {
                    Text = "已发布",
                    Value = "1"
                });
            model.AvailablePublishedOptions.Add(
                new SelectListItem
                {
                    Text = "未发布",
                    Value = "2"
                });

            return View(model);
        }
        
        [HttpPost]
        public ActionResult StockInfo(DataSourceRequest command, ProductListModel model)
        {
            if (!permissionService.Authorize(StandardPermissionProvider.InventoryProduct))
            {
                return AccessDeniedView();
            }
            if (ModelState.IsValid)
            {
                var psm = inventoryService.GetProductInventories(model.SearchProductName,
                    model.SearchCategoryId, model.SearchStoreId);


                var gridModel = new DataSourceResult
                {
                    Data = psm.Select(
                        x => new
                        {
                            ProductName = x.Product.Name,
                            StoreName = x.Store.Name,
                            Quantity = x.Quantity
                        }),
                    Total = psm.Count
                };

                return Json(gridModel);
            }
            return Json(false);
        }

        public ActionResult Warehousing()
        {
            if (!permissionService.Authorize(StandardPermissionProvider.InventoryProduct))
            {
                return AccessDeniedView();
            }

            var model = new InventoryModel();

            var allCategories = categoryService.GetAllCategories();
            foreach (var category in allCategories)
            {
                model.AvailableCategories.Add(
                    new SelectListItem
                    {
                        Text = category.Name,
                        Value = category.Id.ToString()
                    });
            }

            var products = productService.GetAllProducts();

            if (products == null ||
                !products.Any())
            {
                return RedirectToAction("Create");
            }

            products.ToList().ForEach(
                p =>
                {
                    model.AvailableProducts.Add(
                        new SelectListItem
                        {
                            Text = p.Name,
                            Value = p.Id.ToString()
                        });

src/EasyERP.Web/Views/Payment/PayInfo.cshtml
@using EasyErp.Core.Configuration.Settings
@using EasyErp.Core.Infrastructure
@using EasyERP.Web.Framework
@model EasyERP.Web.Models.Payments.PaymentModel
@section SectionTitle
{
   <h1 id="crmTitle">
    <strong>付款信息明细</strong><strong class="pdt-back" style="margin-left:2em;"> <i class="fa fa-reply"></i>@Html.ActionLink("返回入库记录", "InventoryRecords", "Product")</strong>
</h1>
}
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<AreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<AreaSettings>().GridPageSizes;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    if (Model.Paid.Equals(Model.TotalAmount))
    {
        <div class="property-content m-b">
            <label style="font-size:18px; font-weight:600; color:#1872AB;">货款已付清！</label>
        </div>
    }
    <div class="m-b">
        <p>
            <label>总应付款:&nbsp;&nbsp;&nbsp;&nbsp;</label><label style="font-size:24px; font-weight:800;">@Model.TotalAmount</label><label>元</label>
        </p>
    </div>
    <div class="m-b">
        <p>
            <label>已付款:&nbsp;&nbsp;&nbsp;&nbsp;</label><label style="font-size:18px; font-weight:800;">@Model.Paid</label><label>元</label>
        </p>
    </div>
    <div class="m-b" style="color:#EA394C;">
        <p>
            <label>剩余应付:&nbsp;&nbsp;&nbsp;&nbsp;</label><label style="font-size:18px; font-weight:800;">@(Model.TotalAmount - Model.Paid)</label><label>元</label>
        </p>
    </div>
    <div class="m-b" style="color:#1872AB;">
        <p>
            <em>截止日期:</em><em>@Model.DueDateTime</em>
        </p>
    </div>
    <div>
        <p>
            <label>付款信息:</label>
        </p>
    </div>
    <div id="payitems"></div>
    <div id="pay-window"></div>

    <script type="text/x-kendo-template" id="toolbar-template">
        <div class="pay-btn" id="toolbar">
            <button type="button" id="pay-button" class="k-button btn-pay">付款</button>
        </div>
    </script>

    <script id="pay-window-template" type="text/x-kendo-template">
        <div> 
            <p>应付款:<label>@(Model.TotalAmount - Model.Paid)</label></p>
            <p>付款金额:<input type="number" id="pay-amount"></p>
            <p>付款日期:<span id="currentDateTime" /></p>
        </div>
        <div>
            <button id="okayButton" class="k-button">付款</button>
            <button id="cancelButton" class="k-button">取消</button>
        </div>
    </script>
    <script>
        var payinfo = @(Html.ToJson(Model));

        function additionalData() {
            var data = {
                model: payinfo
            };
            addAntiForgeryToken(data);
            return data;
        }

        var payItemsSource = new kendo.data.DataSource({
            transport: {
                read: {
                    url: "/Payment/PayInfo",
                    type: "POST",
                    dataType: "Json",
                    data: additionalData
                }
            },
            schema: {
                model: {
                    fields: {
                        "PayDate": { type: "date" }
                    }
                }
            }
        });

        $("#payitems").kendoGrid({
            dataSource: payItemsSource,
            toolbar: kendo.template($("#toolbar-template").html()),
            columns: [
                { field: "PayDate", title: "付款日期", width: 100, template: '#= kendo.toString(PayDate, "yyyy/M/d H:m:s" ) #' },
                { field: "PayAmount", title: "付款额", width: 100 }
            ]
        });

        function getCurrentDateTime() {
            var currentdate = new Date();
            var datetime = currentdate.getDate() + "/"
                + (currentdate.getMonth() + 1) + "/"
                + currentdate.getFullYear() + " T "
                + currentdate.getHours() + ":"
                + currentdate.getMinutes() + ":"
                + currentdate.getSeconds();
            return datetime;
        }

        $(document).ready(function() {
            if (payinfo.paid === payinfo.totalAmount) {
                $("#toolbar").hide();
            }
        });
    </script>
    <style>
        .toolbar { float: right; }
    </style>
}
@using (Html.BeginForm("Pay", "Payment", FormMethod.Post, new
{
    id = "pay-action"
}))
{
    @Html.AntiForgeryToken()
    <input type="hidden" id="payAmount" name="PayAmount" value=""/>
    <input type="hidden" id="payId" name="Id" value=""/>
}
<script>
    $("#pay-button").click(function() {
        var payWindow = $("#pay-window").kendoWindow({
            title: "付款",
            width: 400,
            height: 300,
            resizeable: false,
            actions: ["Close"],
            modal: true,
            viewable: false,
            visible: false,
            content: { template: $("#pay-window-template").html() }
        }).data("kendoWindow");
        payWindow.open().center();
        $("#currentDateTime").text(getCurrentDateTime());
        $("#pay-amount").attr({
            "max": payinfo.totalAmount - payinfo.paid,
            "min": 1
        });

        $("#okayButton").click(function(e) {
            e.preventDefault();
            var payAmount = $("#pay-amount").val();
            if (!payAmount) {
                $('<span class="text-danger">请输入付款金额</span>').
                    insertAfter('#pay-amount');
                return;
            }

            if (payAmount < 0 || payAmount > payinfo.totalAmount - payinfo.paid) {
                $('<span class="text-danger">数额不正确</span>').
                    insertAfter('#pay-amount');
                return;
            }
            var payId = payinfo.id;
            $("#pay-action #payAmount").val(payAmount);
            $("#pay-action #payId").val(payId);
            $("#pay-action").submit();
            payWindow.close();

        });
        $("#cancelButton").click(function(e) {
            e.preventDefault();
            payWindow.close();
        });

    });
</script>